### ISSUE TITLE
Use underscore routes

### ISSUE THREAD

**Issue by Claudweb** [OrbitalEnterprises/eve-esi-client#1]
Please use `https://esi.tech.ccp.is/_latest/swagger.json` instead of `https://esi.tech.ccp.is/latest/swagger.json` to generate the api.
For detailed reasons please see the [blog post](https://developers.eveonline.com/blog/article/esi-best-practices-using-underscore-routes) by CCP Bartender.

**Comment by deadlybulb** [comment]
Fixed!  Thanks for the heads up.  I've kicked off a new client generation to immediately pick up the changes.  Thanks again!
